security:
    providers:
         telemedicina:
             entity:
                 class: App\Entity\Usuario
                 property: correo
    encoders:
         App\Entity\Usuario:
          algorithm: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: bandeja
            provider: telemedicina
            logout:
                path:   ctrl_logout
                target: ctrl_login    
        
        