security:
    providers:
         telemedicina:
             entity:
                 class: App\Entity\Usuario
                 property: correo
    password_hashers:
        # auto hasher with default options for the User class (and children)
        App\Entity\Usuario: 'auto'

        # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous:    true
            lazy: true
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: bandeja
            provider: telemedicina
            logout:
                path:   ctrl_logout
                target: ctrl_login 
            
    access_control:
        - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/crearcuenta, role: IS_AUTHENTICATED_ANONYMOUSLY }